server.port: 8090
spring:
  ai.mcp.server:
    capabilities:
      completion: true
      prompt: true
      resource: true
      tool: true
    name: mcp-server
    protocol: streamable
    type: SYNC
    version: 0.0.1
    streamable-http:
      mcp-endpoint: /mcp
      keep-alive-interval: 30s
  application.name: mcp-server
  datasource:
    url: jdbc:postgresql://localhost:5342/mcp-server
    username: gilles
    password: password
  liquibase.change-log: classpath:/db/changelog/db.changelog-master.yml
  threads.virtual.enabled: true
  security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:9000

